"""Multi-Domain Adversarial Stress-Testing and Evaluation Module."""
from __future__ import annotations

from pipeline.adversarial.generator import (
    AdversarialMutationEngine,
    generate_adversarial_suite,
    generate_attack_matrix,
)
from pipeline.adversarial.models import (
    AdversarialMutationConfig,
    AttackVectorEnum,
    AttackVectorType,
    CorpusValidationReport,
    DifficultyTierEnum,
    DifficultyTierType,
    DocumentRecord,
    DomainEnum,
    DomainType,
    ExpectedArbiterDecisionType,
    ExpectedDefenseOutcome,
    ExpectedVerdictType,
    GroundTruthFact,
    MultiDomainScenario,
    PoisonedScenarioCase,
    get_scenario,
    get_scenarios_by_domain,
    load_scenario_corpus,
    validate_scenario_corpus,
)
from pipeline.adversarial.mutators import (
    MUTATOR_REGISTRY,
    BaseAdversarialMutator,
    BoundarySaturationMutator,
    CitationDriftMutator,
    NumericTemporalDriftMutator,
    PromptInjectionMutator,
    StatisticalFallacyMutator,
    SyntacticEntanglementMutator,
    get_mutator,
)

__all__ = [
    "MUTATOR_REGISTRY",
    "AdversarialMutationConfig",
    "AdversarialMutationEngine",
    "AttackVectorEnum",
    "AttackVectorType",
    "BaseAdversarialMutator",
    "BoundarySaturationMutator",
    "CitationDriftMutator",
    "CorpusValidationReport",
    "DifficultyTierEnum",
    "DifficultyTierType",
    "DocumentRecord",
    "DomainEnum",
    "DomainType",
    "ExpectedArbiterDecisionType",
    "ExpectedDefenseOutcome",
    "ExpectedVerdictType",
    "GroundTruthFact",
    "MultiDomainScenario",
    "NumericTemporalDriftMutator",
    "PoisonedScenarioCase",
    "PromptInjectionMutator",
    "StatisticalFallacyMutator",
    "SyntacticEntanglementMutator",
    "generate_adversarial_suite",
    "generate_attack_matrix",
    "get_mutator",
    "get_scenario",
    "get_scenarios_by_domain",
    "load_scenario_corpus",
    "validate_scenario_corpus",
]
